<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>p_The product has been added to your shopping cart</name>
   <tag></tag>
   <elementGuidId>65903c4d-7a3b-43b5-a2eb-1f5e65717ca2</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='bar-notification']/p</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>p.content</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>p</value>
      <webElementGuid>9a559de5-f76c-4753-8c11-c0adfa079248</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>content</value>
      <webElementGuid>0b5d5f7e-48d7-4c7d-bbbd-891fdbb78073</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>The product has been added to your shopping cart</value>
      <webElementGuid>d4216f66-24a8-48d0-8921-79ef650f5229</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;bar-notification&quot;)/p[@class=&quot;content&quot;]</value>
      <webElementGuid>cd02a624-4eb0-4c7f-b4b6-73328f28adae</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='bar-notification']/p</value>
      <webElementGuid>ad937ddb-e900-4a19-b45d-5def211f48d8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='niteshtestautomation@abc.com'])[1]/preceding::p[1]</value>
      <webElementGuid>1ce9d17b-d94f-4f44-bacf-adf89cd90f39</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='The product has been added to your']/parent::*</value>
      <webElementGuid>f27e3f3f-1971-47ba-ba1e-1096a138e5eb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//p</value>
      <webElementGuid>560ee585-064a-4d11-b758-b924514d488e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//p[(text() = 'The product has been added to your shopping cart' or . = 'The product has been added to your shopping cart')]</value>
      <webElementGuid>7550ea18-296d-4d1a-98ba-c6eeab50c4a9</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
