<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Fax number_PickUpInStore</name>
   <tag></tag>
   <elementGuidId>edd2d115-9ee2-4d95-8602-d980b6d5ecb8</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='PickUpInStore']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#PickUpInStore</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>53443f1d-afc0-41de-a7a9-d53d8a6b1a08</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>PickUpInStore</value>
      <webElementGuid>7cb2048c-2da8-4670-b2c7-61f0aa6e56c7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>PickUpInStore</value>
      <webElementGuid>559e2aab-514d-4daa-bec5-d6fa9c6eade6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>Shipping.togglePickUpInStore(this)</value>
      <webElementGuid>3e922fe4-c5c9-46b6-bb08-93abd0625e38</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>5fd1d624-d4ed-4086-93fd-a60eeec5cac3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>0408aafe-b93d-436e-a28d-da87e9d2845d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;PickUpInStore&quot;)</value>
      <webElementGuid>7fa52df0-0446-47e3-83e9-3eb83f423914</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='PickUpInStore']</value>
      <webElementGuid>34186197-e853-4de9-a052-a6bd284bcfbe</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='checkout-shipping-load']/div/div[2]/p/input</value>
      <webElementGuid>3fc7b4c0-4ef2-4269-b411-8dfd0d4f7845</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//p/input</value>
      <webElementGuid>466fd042-8a88-4d8d-9e54-1b4138ea1389</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'PickUpInStore' and @name = 'PickUpInStore' and @type = 'checkbox']</value>
      <webElementGuid>a31aca60-d36e-4510-9457-98fa7e72ff30</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
